### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stepan-neretin7** [thec0sm0s/Flask-Discord#12]
Hi, I am again with a stupid question)
How can I correctly and beautifully check which guilds
the user bot is an administrator
I would be grateful if you give advice on how to do it beautifully and quickly)

**Comment by thec0sm0s** [comment]
As far as I know, the API doesn't provides such thing as application/bot being in the guilds. You will have to do it from yout Bot application imo

**Comment by stepan-neretin7** [comment]
@thec0sm0s okey..How can i get auth user token to use it in requests queries?

**Comment by stepan-neretin7** [comment]
More precisely, it turned out to get the token, but the question is .. Is it possible to use the user token to see the participants of the servers he entered

**Comment by thec0sm0s** [comment]
You can get user token from the flask session as: `token = session["DISCORD_OAUTH2_TOKEN"]`.
I think no you can't. You will have to use the Bot application to see the guild members.

Also you can use https://flask-discord.readthedocs.io/en/latest/api.html#flask_discord.DiscordOAuth2Session.request method to make request with the current user OAuth flow to your desired routes.

**Comment by thec0sm0s** [comment]
For future questions, consider asking it in the discord server: https://discord.gg/7CrQEyP
