### ISSUE TITLE
Invalid OAuth2 redirect_uri

### ISSUE THREAD

**Issue by jackdevo** [thec0sm0s/Flask-Discord#16]
My app setup is like this:
```
from flask import Flask, redirect, url_for, render_template, request
from flask_discord import DiscordOAuth2Session
import sqlite3
import math
app = Flask(__name__)
app.secret_key = b"YUGYT76hh6767HT76j7y6thG"
app.config["DISCORD_CLIENT_ID"] = 722199989908013057    # Discord client ID.
app.config["DISCORD_CLIENT_SECRET"] = "vC6kUTAyn_j5BNbBu3AXwkHnAa-xB32G"               
app.config["DISCORD_BOT_TOKEN"] = ""                    # Required when you want to use User.add_to_guild method.
app.config["DISCORD_REDIRECT_URI"] = "http://jackdevo.pythonanywhere.com/callback" #Won't work with localhost as Discord server cannot find i
SQLITE_DIR = "site.db"
```

And I have not changed the callback function. However I always get an Invalid OAuth2 redirect_uri issue when using the /login route. The URL in the browser at the time of the error shows
```https://discord.com/oauth2/authorize?response_type=code&client_id=722199989908013057&redirect_uri=http%3A%2F%2Fjackdevo.pythonanywhere.com%2Fcallback&scope=identify+email+guilds+guilds.join&state=PdYUUyKlEcZEjvF7oC1uIwurlALUCB```

I am really confused as the app seems to be setup correctly but no matter what type of URL I use, http or https, and even without, I get an error.

**Comment by jackdevo** [comment]
Update: I have now tried the test app provided in the repository, and provided my Client ID, Client Secret and a Redirect_URI (http and https), and also a BOT ID but still am getting an error on Discords end.

**Comment by thec0sm0s** [comment]
Can you show what redirect URI is set in Discord developers application OAuth2 settings?

**Comment by thec0sm0s** [comment]
Also reset your client secret please. You seem to have exposed it.

**Comment by jackdevo** [comment]
Reset everything, thanks for the heads up! The redirect URL on the developer app is https://jackdevo.pythonanywhere.com - Again all variations don't work.

**Comment by thec0sm0s** [comment]
The redirect URI in the application page should be exactly same as what you specified in your app configs. It determines the callback URL which will be used by Discord. For your case, its `http://jackdevo.pythonanywhere.com/callback`. Use this.

**Comment by jackdevo** [comment]
Thankyou, must have been a silly mistake on my end :)
