### ISSUE TITLE
Unautorized, when I tried to fetch user

### ISSUE THREAD

**Issue by SQWiperYT** [thec0sm0s/Flask-Discord#18]
Well, my credentials are correct but still I am getting unauthorized error.

**Comment by thec0sm0s** [comment]
Are you sure the OAuth grant was completed and callback function was invoked correctly?

**Comment by SQWiperYT** [comment]
> Are you sure the OAuth grant was completed and callback function was invoked correctly?

I am just trying to use given example.

**Comment by thec0sm0s** [comment]
https://github.com/thec0sm0s/Flask-Discord/issues/6#issuecomment-620400655

**Comment by thec0sm0s** [comment]
As said by Potato, https://github.com/thec0sm0s/Flask-Discord/issues/20#issuecomment-658543581

You need to make sure that your redirect URL points to the callback function of your app.
