### ISSUE TITLE
Unauthorised when trying to get guild roles

### ISSUE THREAD

**Issue by RaVenInTheDark** [thec0sm0s/Flask-Discord#19]
I'm trying to get the guild roles using DiscordOAuth2Session.request, and I'm getting an unauthorised error. I'm guessing this is because my application itself doesn't have authorisation to view the roles, how could I get the roles of a guild in this situation?

**Comment by thec0sm0s** [comment]
The guild roles is not provided as Discord OAuth2. It requires your bot application token to acess such resources rather than authorization token obtained from OAuth2.
Work is in progress to included bot resources which are outside of OAuth resources. I think I will update soon with acess to such models. You can track the progress in dev branch.

**Comment by RaVenInTheDark** [comment]
> The guild roles is not provided as Discord OAuth2. It requires your bot application token to acess such resources rather than authorization token obtained from OAuth2.
> Work is in progress to included bot resources which are outside of OAuth resources. I think I will update soon with acess to such models. You can track the progress in dev branch.

Is there any way (in dev or release branch) I can do this? (With my bot token ofc)

**Comment by thec0sm0s** [comment]
Give me a bit and I will push the working roles model to dev. Then you can follow same pattern if you want other models. 

Anyways if you want you can use this internal method present in dev branch https://github.com/thec0sm0s/Flask-Discord/blob/3ea0fcc44e0f11afbc6f5d3bad5a6a4db9457113/flask_discord/_http.py#L156

Something like:
```python
my_flask_app.config["DISCORD_BOT_TOKEN"] = ""

roles_payload = discord.bot_request("/guilds/{guild.id}/roles")

...
```

**Comment by RaVenInTheDark** [comment]
Thank you! Time to swap to dev branch then aha. Any extra requirements I need to know before swapping?

**Comment by thec0sm0s** [comment]
Don't think so. There's no breaking change there.

**Comment by RaVenInTheDark** [comment]
Seems to have worked! Thank you.

**Comment by RaVenInTheDark** [comment]
Sorry to re-open this, but I thought this would be a suitable place. How could we use post requests with bot_request?

**Comment by thec0sm0s** [comment]
https://github.com/thec0sm0s/Flask-Discord/blob/3ea0fcc44e0f11afbc6f5d3bad5a6a4db9457113/flask_discord/_http.py#L156
It accepts a `method` kwarg which defaults to GET. To make post requests, just pass `method="POST"`. It fundamentaly uses the `requests.request(...)` method and all of the other `**kwargs` of `.bot_request` get passed to `requests.request`. Meaning if you want to pass custom Json payload, you can simply do something like, `.bot.request("/route/", method="POST", json=dict())`.

**Comment by RaVenInTheDark** [comment]
Thank you! I don't think I can close this again on mobile.
