### ISSUE TITLE
Not authorized even though I authorized access to my account

### ISSUE THREAD

**Issue by JT-Potato** [thec0sm0s/Flask-Discord#20]
I am trying to implement sign-in with Discord on a website I am making.
`if discord.authorized == False:
    return redirect(URL BACK TO LOGIN PAGE)
else:
    return <p>You passed authorization</p> #This is just for testing purposes`

And on every case, it redirects me back to Discord's "Authorize access to your account" page.

The login code (Pretty much copy-pasted from the guide)
`@app.route('/')
def login():
  return discord.create_session()

@app.route("/callback/")
def callback():
    discord.callback()
    return redirect(url_for(".me"))`

**Comment by SQWiperYT** [comment]
Same happening with me,
can someone answer what the redirect url should be?

**Comment by SQWiperYT** [comment]
Unauthorized Unauthorized Unauthorized wth dude

**Comment by thec0sm0s** [comment]
Can you share what redirect URL you're passing.

**Comment by JT-Potato** [comment]
If you mean me:
`return redirect('https://creatorcrowdsourcing.jtpotato.repl.co')`
If discord.authorized returns False. That page points to Discord's authorisation page, which should point me to https://creatorcrowdsourcing.jtpotato.repl.co/me unless authorisation fails.

(The flask code for the /me path is here:)
```@app.route('/me/')
def me():
  print(discord.authorized)
  if discord.authorized == False:
    print('Not authed')
    return redirect('https://creatorcrowdsourcing.jtpotato.repl.co')
  else:
    print('Authed')
    user = discord.fetch_user()
    return f"""
    <html>
        <head>
            <title>{user.name}</title>
        </head>
        <body>
            <img src='{user.avatar_url}' />
        </body>
    </html>"""```

The contents of the /me page are temporary, just to make sure Discord auth works - once it does, we can put in the real page.

**Comment by SQWiperYT** [comment]
> If you mean me:
> `return redirect('https://creatorcrowdsourcing.jtpotato.repl.co')`
> If discord.authorized returns False. That page points to Discord's authorisation page, which should point me to https://creatorcrowdsourcing.jtpotato.repl.co/me unless authorisation fails.
> 
> (The flask code for the /me path is here:)
> 
> ```
> def me():
>   print(discord.authorized)
>   if discord.authorized == False:
>     print('Not authed')
>     return redirect('https://creatorcrowdsourcing.jtpotato.repl.co')
>   else:
>     print('Authed')
>     user = discord.fetch_user()
>     return f"""
>     <html>
>         <head>
>             <title>{user.name}</title>
>         </head>
>         <body>
>             <img src='{user.avatar_url}' />
>         </body>
>     </html>"""```
> 
> The contents of the /me page are temporary, just to make sure Discord auth works - once it does, we can put in the real page.
> ```

Same, discord.authorized is always False idk why

**Comment by williamhatcher** [comment]
@SQWiperYT please make your own issue or butt out. Thank you :)

**Comment by SQWiperYT** [comment]
> @SQWiperYT please make your own issue or butt out. Thank you :)

I made one before, but no response at all

**Comment by JT-Potato** [comment]
@williamhatcher I saw the pull request and tried the updated code. So far, it seems like it's a more elegant way to redirect people back to login if they aren't authorized. But I still get redirected every time, so I'm guessing authorization is failing every time?

**Comment by SQWiperYT** [comment]
@JT-Potato #22 Read this...

**Comment by JT-Potato** [comment]
> @JT-Potato #22 Read this...

Yes! Thanks!

SOLUTION:
Add:
`os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'`
And redirect URI should point to /callback
