### ISSUE TITLE
How can i initialize the DiscordOAuth2Session if i have a constructor function?

### ISSUE THREAD

**Issue by alexfrunza** [thec0sm0s/Flask-Discord#25]

**Comment by thec0sm0s** [comment]
Can you please describe and provide more context of what you're trying to do/acheive.

**Comment by thec0sm0s** [comment]
Assuming you've sub-classed the flask app, `flask.Flask`, you can simply do `self.discord = DiscordOAuth2Session(...)` inside your application constructor after loading your configs.

**Comment by alexfrunza** [comment]
For example my code looks like this right now, but i want to initialize the DiscordOAuth2Session like db for example, or is good like i did? the code works fine
`# imports
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
mail = Mail()
migrate = Migrate()

discord_oauth = None


def create_app(config_class=Config):
    global discord_oauth

    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    migrate.init_app(app, db)
    discord_oauth = DiscordOAuth2Session(app)

    from flaskblog.users.routes import users
    app.register_blueprint(users)

    from flaskblog.posts.routes import posts
    app.register_blueprint(posts)

    from flaskblog.main.routes import main
    app.register_blueprint(main)

    from flaskblog.errors.handlers import errors
    app.register_blueprint(errors)

    return app
`

**Comment by thec0sm0s** [comment]
For now, what you did doesn't looks bad and is actually okay. However, if you just want to access it inside your blueprint, you can simply do something like:
```python
from flask import current_app

discord_oauth = current_app.discord

...
```

Flask-Discord implicitly attaches its own instance to the flask application.

**Comment by alexfrunza** [comment]
I tried this solution and i got an error `This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.` and if i try to import app i get a circular import error

**Comment by thec0sm0s** [comment]
I see. Give me a bit, I will push update providing lazy app initialization. Then you might be able to use similar way as you do for db, etc.

**Comment by thec0sm0s** [comment]
Now you should be able to do something like:

```python
import os

from flask import Flask
from flask_discord import DiscordOAuth2Session


discord = DiscordOAuth2Session()


def get_app():
    app = Flask(__name__)

    app.secret_key = b"%\xe0'\x01\xdeH\x8e\x85m|\xb3\xffCN\xc9g"
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "true"  # !! Only in development environment.

    app.config["DISCORD_CLIENT_ID"] = 490732332240863233
    app.config["DISCORD_CLIENT_SECRET"] = os.getenv("DISCORD_CLIENT_SECRET")
    app.config["DISCORD_BOT_TOKEN"] = os.getenv("DISCORD_BOT_TOKEN")
    app.config["DISCORD_REDIRECT_URI"] = "http://127.0.0.1:5000/callback"

    discord.init_app(app)

    return app
```

**Comment by alexfrunza** [comment]
Thanks for help!
