### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by simonsruggi** [thec0sm0s/Flask-Discord#28]
Hello, I get unauthorized exception after login on discord, why?

**Comment by thec0sm0s** [comment]
There could be many reasons but since you haven't described your situation I can assume:
- You might be trying to access resource outside from list of states you passed when creating Discord session.
- Your browser cookies could be missing. There could be many reasons for this.
- User might have revoked your application from their "Authorized Apps".

**Comment by simonsruggi** [comment]
I'm just running a flask app on my localhost. 
Login on endpoint /login and a redirect to /dashboard after the login. But the fetch_user runs the exception "unauthorized" even if I'm logged in

**Comment by thec0sm0s** [comment]
Can you confirm, what state you're passing and what resource you're trying to access after login.

**Comment by simonsruggi** [comment]
application = Flask(__name__)

application.secret_key = b""
#os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "true"      
application.config["DISCORD_CLIENT_ID"] =""  
application.config["DISCORD_CLIENT_SECRET"] =""          
application.config["DISCORD_REDIRECT_URI"] = 'http://127.0.0.1:5000/dashboard'             
application.config["DISCORD_BOT_TOKEN"] = ""                    
discord = DiscordOAuth2Session(application)


@application.route('/dashboard/')
@requires_authorization #tried both with and without
def me():
    
    user = discord.fetch_user()
    
    return f"""
    <html>
        <head>
            <title>{user.name}</title>
        </head>
        <body>
            <img src='{user.avatar_url}' />
        </body>
    </html>"""
    
@application.route('/discordlogin/')

def discordlogin():
    
    return discord.create_session()
	
@application.route('/callback/')
def callback():
    
    discord.callback()
    
    return redirect('/dashboard/')


@application.errorhandler(Unauthorized)
def redirect_unauthorized(e):
    
    
    return 'Unauthorized'

**Comment by thec0sm0s** [comment]
Strange,  no idea what could possibly go wrong. Everything looks fine on here. I am unable to reproduce this situation from my side.

**Comment by simonsruggi** [comment]
Maybe I made some errors in discord developer dashboard? Or maybe python 3.7 / 3.8 (I tried both versions) are not compatible with this module?

**Comment by thec0sm0s** [comment]
I have tested on Python 3.8, no issues here. Yeah I think so, just double check your credentials, etc.

**Comment by thec0sm0s** [comment]
oh my bad F me. Didn't noticed your code properly. Apologies. You have set `http://127.0.0.1:5000/dashboard` as callback. Which means in your case, the code:
```python
@application.route('/callback/')
def callback():
    discord.callback()
    return redirect('/dashboard/')
```
... is never getting executed. You need to set URL for this exact view in your callback. So that it can save the authorization response from Discord.

**Comment by simonsruggi** [comment]
So in this case i need to setup http://127.0.0.1:5000/callback/ as callback?

**Comment by thec0sm0s** [comment]
YES MY FRIEND OH MY GOD YES

**Comment by thec0sm0s** [comment]
ALSO: Exact same URL goes in Discord dev dashboard.

**Comment by simonsruggi** [comment]
Oh, finally it works! Thank you so much :)
