### ISSUE TITLE
Invalid OAuth2 access token

### ISSUE THREAD

**Issue by joelcloud** [thec0sm0s/Flask-Discord#5]
```
def add_to_server(access_token, server_id, user_id):

    url = 'https://discordapp.com/api/guilds/{}/members/{}'.format(server_id, user_id)

    headers = {
        'Authorization': 'Bot XXXXXXXXXXXXXXXXXXXXX',
        'Content-Type': 'application/json'
    }

    data = {
        'access_token': access_token
    }

    add = requests.put(url, headers=headers, json=data)
    print(json.loads(add.text))
```
This gives:
`{'message': 'Invalid OAuth2 access token', 'code': 50025}`

To get the access token and user_id I use:
```
access_token = session['DISCORD_OAUTH2_TOKEN']['access_token']
user = discord.fetch_user() 
user_id = user.id
```

Any idea on how to fix this? Thanks in advance.

**Comment by joelcloud** [comment]
Figured it out! Working now.

**Comment by thec0sm0s** [comment]
Yeah, I checked it myself and got your same code working.
Moreover I have added that method to the User class to make this functionality easier. You can pull the dev branch and try it yourself if you want.
This is the commit which added this method: 57c3d4d5a750302e641829ef77633777f307b544

**Comment by SteveChurch** [comment]
> Figured it out! Working now.

What was the cause for this?
